version: '3.8'

services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: dronecore-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dronecore
      MYSQL_USER: dronecore_user
      MYSQL_PASSWORD: dronecore_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - dronecore-network

  # Backend Node.js
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: dronecore-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://dronecore_user:dronecore_pass@mysql:3306/dronecore
      JWT_SECRET: your-secret-key-change-in-production
      PORT: 3001
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - dronecore-network
    command: npm run dev

  # Frontend React
  frontend:
    build:
      context: ./dronecore-dashboard-ui
      dockerfile: Dockerfile
    container_name: dronecore-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3001/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./dronecore-dashboard-ui:/app
      - /app/node_modules
    networks:
      - dronecore-network
    command: npm run dev

volumes:
  mysql_data:

networks:
  dronecore-network:
    driver: bridge 